Repository boostcampwm-2024/web31-BooLock, pull requests merged in 2024-11, with the labels that each got.

#61 [#59] tailwindCss 디자인 시스템 구축
  .prettierrc
  apps/client/src/app/index.css
  apps/client/tailwind.config.js
  package.json
  pnpm-lock.yaml
Labels: setting

#62 [#60] 아이콘 설정
  apps/client/index.html
  apps/client/package.json
  apps/client/public/icons/example
  apps/client/src/shared/assets/arrow_left.svg
  apps/client/src/shared/assets/arrow_right.svg
  apps/client/src/shared/assets/close.svg
  apps/client/src/shared/assets/code_copy.svg
  apps/client/src/shared/assets/minus_border.svg
  apps/client/src/shared/assets/plus.svg
  apps/client/src/shared/assets/plus_border.svg
  apps/client/src/shared/assets/table_chart.svg
  apps/client/src/shared/assets/tag_container.svg
  apps/client/src/shared/assets/tag_etc.svg
  apps/client/src/shared/assets/tag_form.svg
  apps/client/src/shared/assets/tag_link.svg
  apps/client/src/shared/assets/tag_list.svg
  apps/client/src/shared/assets/tag_text.svg
  apps/client/src/shared/assets/trash.svg
  apps/client/src/vite-env.d.ts
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: chore

#64 [#58] 워크스페이스 헤더 정적 UI 구현
  apps/client/src/app/index.css
  apps/client/src/features/example
  apps/client/src/features/index.ts
  apps/client/src/features/workspace/RedoButton.tsx
  apps/client/src/features/workspace/SaveButton.tsx
  apps/client/src/features/workspace/UndoButton.tsx
  apps/client/src/features/workspace/WorkspaceNameInput.tsx
  apps/client/src/shared/assets/arrow_left.svg
  apps/client/src/shared/assets/arrow_right.svg
  apps/client/src/shared/assets/boolock_logo.svg
  apps/client/src/shared/ui/button/CircleButton.tsx
  apps/client/src/shared/ui/index.ts
  apps/client/src/vite-env.d.ts
  apps/client/src/widgets/workspace/WorkspaceHeader.tsx
  apps/client/vite.config.ts
Labels: FE, feat

#63 [#2] swagger autogen 설정 및 storybook 설정
  .gitignore
  apps/client/.storybook/main.js
  apps/client/.storybook/preview.js
  apps/client/package.json
  apps/client/src/entities/ExampleButton.stories.tsx
  apps/client/src/entities/ExampleButton.tsx
  apps/client/src/entities/example
  apps/server/package.json
  apps/server/src/app.ts
  apps/server/src/docs/swagger-output.json
  apps/server/src/docs/swagger.ts
  apps/server/src/docs/swaggerAutogen.ts
  apps/server/src/routes/v1/exampleRoute.ts
  apps/server/src/routes/v1/index.ts
  package.json
  packages/tsconfig/tsconfig.node.json
  pnpm-lock.yaml
Labels: FE, BE, setting

#71 [#57] 빈 워크스페이스 영역
  apps/client/src/entities/home/GuideVideo.stories.tsx
  apps/client/src/shared/assets/empty_workspace.svg
  apps/client/src/shared/assets/hovered_empty_workspace.svg
  apps/client/src/widgets/home/EmptyWorkspace.stories.tsx
  apps/client/src/widgets/home/EmptyWorkspace.tsx
  apps/client/src/widgets/index.ts
Labels: FE, test

#73 [#67] 백엔드 mongoDB 연동
  apps/server/package.json
  apps/server/src/app.ts
  apps/server/src/config/dbConnection.ts
  apps/server/src/config/example.ts
  apps/server/src/controllers/exampleController.ts
  apps/server/src/docs/swagger-output.json
  apps/server/src/docs/swagger.ts
  apps/server/src/docs/swaggerAutogen.ts
  apps/server/src/models/exampleModel.ts
  apps/server/src/routes/v1/exampleRoute.ts
  apps/server/src/services/exampleService.ts
  pnpm-lock.yaml
Labels: BE, setting

#77 [#39] 워크스페이스 이름 변경 토스트 메세지 기능 추가 및 HomePage Css 수정
  apps/client/package.json
  apps/client/public/images/boolock_logo.png
  apps/client/public/images/empty_logo.png
  apps/client/public/images/not_found.png
  apps/client/src/app/App.tsx
  apps/client/src/entities/home/HoveredEmptyWorkspace.tsx
  apps/client/src/entities/home/NotHoveredEmptyWorkspace.tsx
  apps/client/src/entities/home/WorkspaceAddBtn.tsx
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/RedoButton.tsx
  apps/client/src/entities/workspace/SaveButton.tsx
  apps/client/src/entities/workspace/UndoButton.tsx
  apps/client/src/entities/workspace/WorkspaceNameInput.tsx
  apps/client/src/features/index.ts
  apps/client/src/features/workspace/WorkspaceNameInput.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/pages/NotFound.tsx
  apps/client/src/pages/index.ts
  apps/client/src/pages/index.tsx
  apps/client/src/shared/assets/boolock_icon.svg
  apps/client/src/shared/assets/empty_workspace.svg
  apps/client/src/shared/assets/hovered_empty_workspace.svg
  apps/client/src/shared/assets/not_found_icon.svg
  apps/client/src/shared/assets/plus_green.svg
  apps/client/src/shared/ui/logo/Logo.tsx
  apps/client/src/widgets/home/EmptyWorkspace.tsx
  apps/client/src/widgets/home/GuidesBox.tsx
  apps/client/src/widgets/home/HomeHeader.tsx
  apps/client/src/widgets/home/WorkspaceHeader.tsx
  apps/client/src/widgets/home/WorkspaceList.tsx
  apps/client/src/widgets/workspace/WorkspacePageHeader.tsx
  pnpm-lock.yaml
Labels: FE, feat

#72 [#69] 워크스페이스 삭제시 재확인 모달
  apps/client/src/entities/home/WorkspaceItem.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/shared/assets/booduck_front.svg
  apps/client/src/shared/store/example
  apps/client/src/shared/store/useModalStore.ts
  apps/client/src/shared/ui/button/SquareButton.tsx
  apps/client/src/shared/ui/index.ts
  apps/client/src/shared/ui/modal/ModalConfirm.tsx
  apps/client/src/widgets/home/WorkspaceModal.tsx
  apps/client/src/widgets/index.ts
Labels: FE

#81 [#80] CODEOWNER 추가
  .github/CODEOWNERS
Labels: setting

#84 [#22] Blockly 기본 틀 구현
  apps/client/src/pages/WorkspacePage.tsx
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/htmlCodeGenerator.ts
Labels: FE

#85 [#83] db 연동 구조 변경 및 코드 수정
  apps/server/package.json
  apps/server/src/config/dbConnection.ts
  pnpm-lock.yaml
Labels: BE, refactor, setting

#86 [#3] 워크스페이스 생성 기능 구현
  apps/client/package.json
  apps/client/src/app/App.tsx
  apps/client/src/app/main.tsx
  apps/client/src/entities/home/HoveredEmptyWorkspace.tsx
  apps/client/src/entities/home/WorkspaceAddBtn.tsx
  apps/client/src/entities/home/WorkspaceItem.tsx
  apps/client/src/entities/workspace/WorkspaceNameInput.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/shared/api/axiosInstance.ts
  apps/client/src/shared/api/example
  apps/client/src/shared/api/index.ts
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/queries/useCreateWorkspace.ts
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useLoadingStore.ts
  apps/client/src/shared/types/example
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/workspaceType.ts
  apps/client/src/shared/ui/button/CircleButton.tsx
  apps/client/src/shared/ui/index.ts
  apps/client/src/shared/ui/loading/Loading.tsx
  apps/client/src/shared/ui/toast/ToasterWithMax.tsx
  apps/server/package.json
  apps/server/src/app.ts
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/models/workspaceModel.ts
  apps/server/src/routes/v1/index.ts
  apps/server/src/routes/v1/workspaceRoute.ts
  apps/server/src/services/workspaceService.ts
  apps/server/src/utils/error_message.ts
  pnpm-lock.yaml
Labels: FE, BE, feat

#87 [#24] 사용자는 “HTML” 탭을 누르면 현재 블록의 html 코드를 볼 수 있다.
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/htmlCodeGenerator.ts
Labels: FE, feat

#88 [🚨 !HOTFIX!] swagger autogen이 주석처리 설정을 못읽어오던 오류 해결
  apps/server/src/controllers/exampleController.ts
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/docs/swagger-output.json
  apps/server/src/docs/swagger.ts
  apps/server/src/docs/swaggerAutogen.ts
  apps/server/src/routes/v1/exampleRoute.ts
  apps/server/src/routes/v1/workspaceRoute.ts
Labels: fix

#92 [#12] 워크스페이스 불러오기 기능 및 무한스크롤 기능 구현
  apps/client/public/images/booduck_modal.png
  apps/client/src/entities/home/WorkspaceItem.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/assets/booduck_front.svg
  apps/client/src/shared/assets/picture_icon.svg
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/queries/useCreateWorkspace.ts
  apps/client/src/shared/hooks/queries/useGetWorkspaceList.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/workspaceType.ts
  apps/client/src/shared/ui/index.ts
  apps/client/src/shared/ui/skeleton/SkeletonWorkspace.tsx
  apps/client/src/shared/ui/skeleton/SkeletonWorkspaceList.tsx
  apps/client/src/shared/utils/index.ts
  apps/client/src/shared/utils/userId.ts
  apps/client/src/widgets/home/EmptyWorkspace.tsx
  apps/client/src/widgets/home/WorkspaceContainer.tsx
  apps/client/src/widgets/home/WorkspaceGrid.tsx
  apps/client/src/widgets/home/WorkspaceList.tsx
  apps/client/src/widgets/home/WorkspaceModal.tsx
  apps/client/src/widgets/index.ts
  apps/server/package.json
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/models/workspaceModel.ts
  apps/server/src/routes/v1/workspaceRoute.ts
  apps/server/src/services/workspaceService.ts
  package.json
  pnpm-lock.yaml
Labels: FE, feat

#93 [#18] “미리보기”, “HTML”, “CSS” 총 3개의 탭을 볼 수 있다.
  apps/client/src/app/index.css
  apps/client/src/widgets/workspace/CssPropsSelectBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
Labels: FE

#94 [#23] 툴박스 카테고리 리스트 커스텀
  apps/client/public/icons/close.svg
  apps/client/src/app/index.css
  apps/client/src/shared/utils/category_icons.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/customCategory.ts
Labels: FE

#99 깃허브 액션 테스트
  .github/workflows/boolock-dev-cicd.yml
Labels: CICD

#100 [#8] 워크스페이스 페이지 이동 기능, 워크스페이스 이름 변경 기능 구현
  .github/workflows/boolock-dev-cicd.yml
  .gitignore
  apps/client/package.json
  apps/client/src/entities/home/WorkspaceItem.tsx
  apps/client/src/entities/home/WorkspaceLoadError.tsx
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/WorkspaceNameInput.tsx
  apps/client/src/pages/WorkspacePage.tsx
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/assets/spinner.svg
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/hooks/queries/useGetWorkspaceList.ts
  apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useWorkspaceStore.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/workspaceType.ts
  apps/client/src/shared/ui/toast/ToasterWithMax.tsx
  apps/client/src/shared/utils/dateFormat.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/shared/utils/userId.ts
  apps/client/src/widgets/home/WorkspaceContainer.tsx
  apps/client/src/widgets/home/WorkspaceList.tsx
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/docs/swagger-output.json
  apps/server/src/docs/swagger.ts
  apps/server/src/routes/v1/workspaceRoute.ts
  apps/server/src/services/workspaceService.ts
  apps/server/src/utils/error_message.ts
  pnpm-lock.yaml
Labels: FE, BE, feat

#102 [hotfix] 누락된 패키지 설치 및 package 스크립트 수정
  apps/server/package.json
  package.json
  pnpm-lock.yaml
Labels: fix

#106 [#105] Spinner 컴포넌트에 CSS 동적으로 적용되지 않는 문제 해결
  apps/client/src/entities/workspace/WorkspaceNameInput.tsx
  apps/client/src/shared/ui/loading/Spinner.tsx
  apps/client/src/shared/utils/categoryIcons.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/shared/utils/spinnerStyle.ts
  apps/client/src/widgets/home/WorkspaceModal.tsx
Labels: FE, fix

#109 [#36] class 블록 동적 생성
  apps/client/src/pages/NotFound.tsx
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/CssPropsSelectBox.tsx
  apps/client/src/widgets/workspace/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/blockly/categoryColours.ts
  apps/client/src/widgets/workspace/blockly/classMakerPrompt.ts
  apps/client/src/widgets/workspace/blockly/customCategory.ts
  apps/client/src/widgets/workspace/blockly/customizeFlyoutSVG.ts
  apps/client/src/widgets/workspace/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/blockly/htmBlockContents.ts
  apps/client/src/widgets/workspace/blockly/htmlCodeGenerator.ts
  apps/client/src/widgets/workspace/blockly/initTheme.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig2.ts
Labels: FE, feat

#111 [#21] 사용자는 “미리보기” 탭을 누르면 블록으로 만든 웹 사이트를 미리 볼 수 있다.
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useClassBlockStore.ts
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/blockly/classMakerPrompt.ts
  apps/client/src/widgets/workspace/blockly/customFlyout.ts
  apps/client/src/widgets/workspace/blockly/customToolbox.ts
  apps/client/src/widgets/workspace/blockly/customizeFlyoutSVG.ts
  apps/client/src/widgets/workspace/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig2.ts
Labels: FE, refactor, feat, fix

#113 [#37] CSS 속성 편집 기능 및 CSS 코드 생성 기능 추가
  apps/client/src/app/index.css
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/CssCategoryButton.tsx
  apps/client/src/entities/workspace/CssOptionItem.tsx
  apps/client/src/entities/workspace/CssTooltip.tsx
  apps/client/src/pages/WorkspacePage.tsx
  apps/client/src/shared/hooks/css/useCssOptionItem.ts
  apps/client/src/shared/hooks/css/useCssOptions.ts
  apps/client/src/shared/hooks/css/useCssTooltip.ts
  apps/client/src/shared/hooks/css/useWindowSize.ts
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useCssPropsStore.ts
  apps/client/src/shared/store/useCssTooptipStore.ts
  apps/client/src/shared/types/cssCategoryType.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/utils/cssCategoryList.ts
  apps/client/src/shared/utils/debounce.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/CssPropsSelectBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/css/CssCategoryBar.tsx
  apps/client/src/widgets/workspace/css/CssOptionItemList.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBox.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader.tsx
  apps/client/src/widgets/workspace/css/cssCodeGenerator.ts
Labels: FE, feat

#112 tab 툴박스 plugin옵션으로 연결하도록 변경
  apps/client/src/app/index.css
  apps/client/src/core/customCategory.ts
  apps/client/src/core/dom.ts
  apps/client/src/core/fixedFlyout.ts
  apps/client/src/core/tabbedToolbox.ts
  apps/client/src/core/wrapBlocklyBlocksInDiv.ts
  apps/client/src/shared/types/extendedType.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/tabType.ts
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/blockly/customToolbox.ts
  apps/client/src/widgets/workspace/customCategory.ts
Labels: refactor

#121 [#28] 블록 커스텀
  apps/client/src/core/customConstantProvider.ts
  apps/client/src/core/customFieldLabel.ts
  apps/client/src/core/customFieldLabelSerializable.ts
  apps/client/src/core/customFieldTextInput.ts
  apps/client/src/core/customRenderInfo.ts
  apps/client/src/core/customRenderer.ts
  apps/client/src/shared/utils/boolockConstants.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/blockly/classMakerPrompt.ts
  apps/client/src/widgets/workspace/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/blockly/htmBlockContents.ts
  apps/client/src/widgets/workspace/blockly/htmlCodeGenerator.ts
  apps/client/src/widgets/workspace/blockly/initTheme.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig2.ts
Labels: FE, feat

#128 [#23] html/css 탭으로 이동해서 html 블록과 스타일 클래스 확인하기
  apps/client/src/app/index.css
  apps/client/src/core/customCategory.ts
  apps/client/src/core/customFieldLabel.ts
  apps/client/src/core/dom.ts
  apps/client/src/core/fixedFlyout.ts
  apps/client/src/core/register.ts
  apps/client/src/core/styleFlyout.ts
  apps/client/src/core/tabbedToolbox.ts
  apps/client/src/core/wrapBlocklyBlocksInDiv.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/tabType.ts
  apps/client/src/shared/utils/tags.ts
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/blockly/classMakerPrompt.ts
  apps/client/src/widgets/workspace/blockly/cssStyleToolboxConfig.ts
  apps/client/src/widgets/workspace/blockly/htmlBlockContents.ts
  apps/client/src/widgets/workspace/blockly/htmlTagToolboxConfig.ts
  apps/client/src/widgets/workspace/blockly/tabConfig.ts
  apps/client/src/widgets/workspace/blockly/toolboxConfig2.ts
Labels: FE

#120 [#43] 사용자는 커스텀한 "CSS 스타일" 탭 창을 볼 수 있다.
  .github/CODEOWNERS
  apps/client/src/app/index.css
  apps/client/src/core/fieldClickableImage.ts
  apps/client/src/core/styleFlyout.ts
  apps/client/src/shared/assets/css_class_delete_icon.svg
  apps/client/src/shared/store/useClassBlockStore.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/styleToolboxType.ts
  apps/client/src/shared/utils/tags.ts
  apps/client/src/widgets/workspace/blockly/cssStyleToolboxConfig.ts
  apps/client/src/widgets/workspace/blockly/tabConfig.ts
Labels: FE, feat

#132 [#130] 사용자는 HTML/CSS 코드를 코드 블록으로 확인할 수 있다.
  apps/client/package.json
  apps/client/src/widgets/workspace/PreviewBox.tsx
  pnpm-lock.yaml
Labels: FE, feat

#136 [#30] br / hr 태그 한 줄 태그로 수정 + 불필요한 form 태그 삭제
  apps/client/src/shared/types/blockType.ts
  apps/client/src/shared/utils/categoryIcons.ts
  apps/client/src/widgets/workspace/blockly/categoryColours.ts
  apps/client/src/widgets/workspace/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/blockly/htmlBlockContents.ts
  apps/client/src/widgets/workspace/blockly/htmlCodeGenerator.ts
  apps/client/src/widgets/workspace/blockly/htmlTagToolboxConfig.ts
Labels: FE, chore

#137 [#129] 스크롤을 내리면 블록 드래그 위치 이상해지는 버그 수정
  apps/client/src/core/fixedFlyout.ts
Labels: bug

#139 [#40] 사용자는 기본으로 적용된 스타일을 [CSS RESET] 체크하여 초기화할 수 있다.
  apps/client/src/app/index.css
  apps/client/src/core/customConstantProvider.ts
  apps/client/src/core/customFieldLabelSerializable.ts
  apps/client/src/core/fieldClickableImage.ts
  apps/client/src/core/styleFlyout.ts
  apps/client/src/entities/ExampleButton.stories.tsx
  apps/client/src/entities/ExampleButton.tsx
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/CssOptionItem.tsx
  apps/client/src/entities/workspace/CssTooltip.tsx
  apps/client/src/entities/workspace/RenderResetCssTooltip.tsx
  apps/client/src/shared/assets/x_icon.svg
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useResetCssStore.ts
  apps/client/src/shared/utils/resetCss.ts
  apps/client/src/widgets/workspace/PreviewBox.tsx
  apps/client/src/widgets/workspace/blockly/customFlyout.ts
  apps/client/src/widgets/workspace/blockly/initTheme.ts
  apps/client/src/widgets/workspace/customCategory.ts
Labels: FE, feat

#142 [#26] 워크스페이스 블록 삭제, 스케일 조정 기능 설정 및 커스텀
  .github/workflows/boolock-dev-cicd.yml
  apps/client/src/app/index.css
  apps/client/src/core/customFieldLabel.ts
  apps/client/src/core/customTrashcan.ts
  apps/client/src/core/customZoomControls.ts
  apps/client/src/core/register.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
Labels: FE, feat

#144 [#34] undo/redo 기능 추가
  apps/client/src/entities/workspace/RedoButton.tsx
  apps/client/src/entities/workspace/UndoButton.tsx
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useWorkspaceStore.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
Labels: FE, feat, fix

#143 [#29] HTML/CSS 탭에서 코드 복사
  apps/client/src/shared/assets/code_copy.svg
  apps/client/src/widgets/workspace/PreviewBox.tsx
Labels: FE, feat

#147 [#138] flyout 처음 랜더링시에 높이 이상한 버그 수정
  apps/client/src/core/fixedFlyout.ts
Labels: bug

#146 [#74] prettier + eslint + husky
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .npmrc
  .prettierignore
  .vscode/settings.json
  README.md
  apps/client/eslint.config.js
  apps/client/package.json
  apps/client/postcss.config.js
  apps/client/src/core/customConstantProvider.ts
  apps/client/src/pages/NotFound.tsx
  apps/client/src/widgets/workspace/blockly/htmlCodeGenerator.ts
  apps/client/src/widgets/workspace/blockly/initBlocks.ts
  apps/client/tsconfig.json
  apps/client/vite.config.ts
  apps/server/eslint.config.js
  apps/server/package.json
  apps/server/src/models/exampleModel.ts
  apps/server/src/services/exampleService.ts
  package.json
  packages/eslint/index.js
  packages/eslint/package.json
  packages/tsconfig/tsconfig.app.json
  packages/tsconfig/tsconfig.node.json
  pnpm-lock.yaml
  scripts/check-branch-name.js
Labels: setting

#154 [#46] 사용자는 삭제 버튼을 통해 클래스 블록을 삭제할 수 있다.
  apps/client/src/app/index.css
  apps/client/src/core/fixedFlyout.ts
  apps/client/src/core/styleFlyout.ts
  apps/client/src/shared/utils/cssClassName.ts
  apps/server/eslint.config.mjs
Labels: FE, feat

#159 [#157] 워크스페이스 이름 변경 시 상태 관리 미적용, 워크스페이스에 저장된 블록이 있음에도 새로 고침 시 초기화 되는 문제 해결
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
  apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
  apps/client/src/shared/types/workspaceType.ts
  apps/client/src/widgets/workspace/WorkspaceContent.tsx
  apps/server/src/services/workspaceService.ts
Labels: fix

#160 [#140] SEO
  apps/client/index.html
  apps/client/package.json
  apps/client/public/images/boolock_thumnail.png
  apps/client/public/robots.txt
  apps/client/src/app/main.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/pages/NotFound.tsx
  apps/client/src/pages/WorkspacePage.tsx
  apps/client/src/shared/ui/logo/Logo.tsx
  pnpm-lock.yaml
Labels: refactor

#161 [#151] 블록 삭제 막기
  apps/client/src/shared/blockly/initBlocks.ts
Labels: bug

#168 [#165] https 환경으로 배포
  .github/workflows/boolock-dev-cicd.yml
  .gitignore
  apps/client/Dockerfile
  apps/client/nginx.conf
  docker-compose.yml
Labels: BE, CICD

#163 [#134] 블록에서 태그 이름이 잘리는 버그 해결
  apps/client/src/core/customFieldTextInput.ts
  apps/client/src/core/customRenderInfo.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/shared/utils/typeGuard.ts
Labels: FE, fix

#179 [#178] 워크스페이스화면에서 로고 이미지가 깨져보이는 오류 해결
  apps/client/src/entities/home/NotHoveredEmptyWorkspace/NotHoveredEmptyWorkspace.tsx
  apps/client/src/entities/home/WorkspaceLoadError/WorkspaceLoadError.tsx
  apps/client/src/pages/NotFound/NotFound.tsx
  apps/client/src/shared/ui/logo/Logo.tsx
  apps/client/src/shared/ui/modal/ModalConfirm.stories.tsx
  apps/client/src/widgets/home/HomeHeader/HomeHeader.tsx
  apps/client/src/widgets/home/WorkspaceModal/WorkspaceModal.tsx
Labels: FE, fix

#180 [#176] html generator 적용 에러
  apps/client/src/core/styleFlyout.ts
  apps/client/src/shared/blockly/htmlCodeGenerator.ts
  apps/client/src/shared/blockly/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: bug, fix
