Repository boostcampwm-2024/web31-BooLock, pull requests merged in 2024-12, with the labels that each got.

#182 [#175] 워크스페이스 저정 버튼 클릭 시 미리보기 창 캡처 및 썸네일 적용
  apps/client/package.json
  apps/client/src/entities/home/WorkspaceItem/WorkspaceItem.tsx
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
  apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/server/package.json
  apps/server/src/config/s3.ts
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/routes/v1/workspaceRoute.ts
  apps/server/src/services/workspaceService.ts
  packages/eslint/index.js
  pnpm-lock.yaml
Labels: FE, BE, feat

#181 [#177] 페이지별 ErrorElement 추가
  apps/client/src/app/App.tsx
  apps/client/src/app/index.css
  apps/client/src/entities/workspace/WorkspaceNameInput/WorkspaceNameInput.tsx
  apps/client/src/pages/ErrorPage/ErrorPage.tsx
  apps/client/src/pages/NotFound/NotFound.tsx
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/hooks/queries/useGetWorkspaceList.ts
  apps/client/src/shared/ui/error/ErrorContent.tsx
  apps/client/src/widgets/home/HomeHeader/HomeHeader.tsx
Labels: bug, FE, refactor, feat

#192 [#187] 폰트 선택 기능 추가
  apps/client/src/shared/utils/cssCategoryList.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
Labels: FE, feat

#193 [#188] 클래스 블록 생성 시 blockly 기본 블록이 생성되는 문제 해결, 워크스페이스 초기 로딩 시 변경사항 감지 문제 해결
  apps/client/src/core/styleFlyout.ts
  apps/client/src/shared/blockly/createCssClassBlock.ts
  apps/client/src/shared/blockly/cssCodeGenerator.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/store/useClassBlockStore.ts
  apps/client/src/shared/utils/boolockConstants.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader/CssPropsSelectBoxHeader.tsx
Labels: bug, FE

#194 [#150] 코드 하이라이팅 구현
  apps/client/index.html
  apps/client/src/shared/blockly/calculateBlockLength.ts
  apps/client/src/shared/blockly/findBlockStartLine.ts
  apps/client/src/shared/blockly/htmlCodeGenerator.ts
  apps/client/src/shared/blockly/index.ts
  apps/client/src/shared/code-highlighter/components/CodeContent.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
  apps/client/src/shared/code-highlighter/components/LineNumbers.tsx
  apps/client/src/shared/code-highlighter/index.ts
  apps/client/src/shared/code-highlighter/styles/CodeViewer.module.css
  apps/client/src/shared/code-highlighter/utils/parseHighlightCss.ts
  apps/client/src/shared/code-highlighter/utils/parseHighlightHtml.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: FE, feat

#195 [#186] select 버그 수정
  apps/client/index.html
  apps/client/src/shared/hooks/css/useCssOptionItem.ts
  apps/client/src/shared/ui/select/Select.tsx
Labels: bug

#196 flyout 크기 고정
  apps/client/src/core/fixedFlyout.ts
Labels: FE, fix

#199 [#198] 누락된 CSS 하이라이팅 기능 추가
  apps/client/src/shared/blockly/htmlCodeGenerator.ts
  apps/client/src/shared/code-highlighter/components/CodeContent.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
  apps/client/src/shared/code-highlighter/utils/parseHighlightCss.ts
  apps/client/src/shared/code-highlighter/utils/parseHighlightHtml.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: FE, refactor

#204 [추가 작업] 누락된 CSS 하이라이팅 기능 추가
  apps/client/src/entities/home/WorkspaceItem/WorkspaceItem.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: fix

#211 [#202] 워크스페이스 목록에서 샘플 이미지 깨지는 문제 해결, 미리보기 캡처 시 css 적용 안되는 문제 해결 및 자잘한 버그 해결
  apps/client/src/app/index.css
  apps/client/src/core/styleFlyout.ts
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/entities/workspace/WorkspaceNameInput/WorkspaceNameInput.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
  apps/client/src/shared/hooks/queries/useCreateWorkspace.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
  apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
  apps/client/src/shared/store/useClassBlockStore.ts
  apps/client/src/shared/store/useWorkspaceStore.ts
  apps/client/src/shared/utils/capturePreview.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader/CssPropsSelectBoxHeader.tsx
  apps/server/package.json
  apps/server/src/services/workspaceService.ts
  pnpm-lock.yaml
Labels: bug, FE, fix

#214 [HOTFIX] 스토리북 이미지 깨짐 문제 해결
  apps/client/public/images/booduck_modal.png
  apps/client/public/images/boolock_logo.png
  apps/client/public/images/boolock_thumnail.png
  apps/client/public/images/empty_logo.png
  apps/client/public/images/not_found.png
  apps/client/src/entities/home/NotHoveredEmptyWorkspace/NotHoveredEmptyWorkspace.tsx
  apps/client/src/entities/home/WorkspaceLoadError/WorkspaceLoadError.tsx
  apps/client/src/shared/ui/error/ErrorContent.tsx
  apps/client/src/shared/ui/logo/Logo.tsx
  apps/client/src/shared/ui/modal/ModalConfirm.stories.tsx
  apps/client/src/widgets/home/WorkspaceModal/WorkspaceModal.tsx
Labels: FE, fix

#215 [#203] main banner 제작
  README.md
  apps/client/src/app/index.css
  apps/client/src/pages/HomePage/HomePage.tsx
  apps/client/src/shared/ui/error/ErrorContent.tsx
  apps/client/src/widgets/home/Banner/Banner.tsx
  apps/client/src/widgets/home/HomeHeader/HomeHeader.tsx
  apps/client/src/widgets/index.ts
Labels: FE, feat

#206 [#35] 추가 태그 블록 제작
  README.md
  apps/client/src/app/index.css
  apps/client/src/core/customFieldImageButton.ts
  apps/client/src/core/customFieldTextInput.ts
  apps/client/src/core/customOptionFieldLabel.ts
  apps/client/src/core/customRenderInfo.ts
  apps/client/src/core/customTagFieldLabel.ts
  apps/client/src/core/register.ts
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/CssTooltip/CssTooltip.tsx
  apps/client/src/entities/workspace/ImageTagModalButton/ImageTagModalButton.tsx
  apps/client/src/entities/workspace/ImageTagModalHeader/ImageTagModalHeader.tsx
  apps/client/src/entities/workspace/ImageTagModalImg/ImageTagModalImg.tsx
  apps/client/src/entities/workspace/ImageTagModalList/ImageTagModalList.tsx
  apps/client/src/entities/workspace/ImageTagModalListItem/ImageTagModalListItem.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/shared/api/workspaceApi.ts
  apps/client/src/shared/assets/x_icon.svg
  apps/client/src/shared/blockly/calculateBlockLength.ts
  apps/client/src/shared/blockly/defineBlocks.ts
  apps/client/src/shared/blockly/htmlBlockContents.ts
  apps/client/src/shared/blockly/htmlCodeGenerator.ts
  apps/client/src/shared/code-highlighter/utils/parseHighlightHtml.ts
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/queries/useDeleteImage.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/hooks/queries/usePostImage.ts
  apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useImageModalStore.ts
  apps/client/src/shared/store/useModalStore.ts
  apps/client/src/shared/types/imageTagType.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/types/workspaceType.ts
  apps/client/src/shared/ui/modal/ModalConfirm.tsx
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/ImageTagModal/ImageTagModal.tsx
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/middlewares/errorMiddleware.ts
  apps/server/src/models/workspaceModel.ts
  apps/server/src/routes/v1/workspaceRoute.ts
  apps/server/src/services/workspaceService.ts
Labels: FE, BE, feat

#217 [#183] 사용자 가이드
  README.md
  apps/client/src/app/index.css
  apps/client/src/core/tabbedToolbox.ts
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
  apps/client/src/shared/store/useCoachMarkStore.ts
  apps/client/src/shared/ui/button/CircleButton.tsx
  apps/client/src/shared/utils/coachMarkContent.tsx
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.tsx
  apps/client/src/widgets/workspace/WorkspacePageHeader/WorkspacePageHeader.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBox/CssPropsSelectBox.tsx
  apps/server/src/controllers/workspaceController.ts
  apps/server/src/services/workspaceService.ts
Labels: FE, feat

#221 [HOTFIX] 워크스페이스 처음 생성시 에러 해결
  apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
Labels: bug, FE

#226 [#224] 자잘한 버그 수정
  apps/client/src/core/tabbedToolbox.ts
  apps/client/src/entities/home/WorkspaceItem/WorkspaceItem.tsx
  apps/client/src/shared/blockly/categoryColours.ts
  apps/client/src/shared/blockly/htmlBlockContents.ts
  apps/client/src/shared/blockly/htmlTagToolboxConfig.ts
  apps/client/src/shared/types/blockType.ts
  apps/client/src/widgets/home/WorkspaceContainer/WorkspaceContainer.tsx
  apps/client/src/widgets/home/WorkspaceGrid/WorkspaceGrid.tsx
  apps/client/src/widgets/home/WorkspaceList/WorkspaceList.tsx
Labels: bug, FE

#225 [#223] 코드 내보내기 버튼 추가
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.stories.tsx
  apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.tsx
  apps/client/src/entities/workspace/ImageTagModalList/ImageTagModalList.tsx
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useIframeStore.ts
  apps/client/src/shared/utils/capturePreview.ts
  apps/client/src/shared/utils/exportPreviewHtml.ts
  apps/client/src/shared/utils/iframeErrorMessage.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.tsx
  apps/server/src/services/workspaceService.ts
Labels: FE, feat

#227 [#164] 워크스페이스 캔버스 모션 설정 변경
  apps/client/src/shared/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: FE, feat

#229 [HOTFIX] CSS 변경사항 감지 로직 변경
  apps/client/src/core/styleFlyout.ts
Labels: FE, fix

#230 [hotfix] favicon, 썸네일 이미지 파일 추가
  apps/client/public/images/boolock_logo.png
  apps/client/public/images/boolock_thumnail.png
Labels: FE, fix

#232 [hotfix] 워크스페이스 페이지 조회 시 css클래스 블록을 전부 불러오지 못하는 문제 해결
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: FE, fix

#234 [#201] Lighthouse 기반 최적화
  apps/client/src/app/App.tsx
  apps/client/src/entities/home/WorkspaceAddBtn/WorkspaceAddBtn.tsx
  apps/client/src/entities/home/WorkspaceItem/WorkspaceItem.tsx
  apps/client/src/entities/home/WorkspaceSampleButton/WorkspaceSampleButton.tsx
  apps/client/src/entities/workspace/CssCategoryButton/CssCategoryButton.tsx
  apps/client/src/entities/workspace/ImageTagModalButton/ImageTagModalButton.tsx
  apps/client/src/entities/workspace/ImageTagModalList/ImageTagModalList.tsx
  apps/client/src/entities/workspace/RedoButton/RedoButton.tsx
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/entities/workspace/UndoButton/UndoButton.tsx
  apps/client/src/shared/ui/button/CircleButton.tsx
  apps/client/src/shared/ui/button/SquareButton.tsx
  apps/client/src/shared/ui/select/Select.tsx
  apps/client/src/widgets/home/WorkspaceGrid/WorkspaceGrid.tsx
  apps/client/src/widgets/home/WorkspaceModal/WorkspaceModal.tsx
  apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
  apps/client/src/widgets/workspace/ImageTagModal/ImageTagModal.tsx
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspacePageHeader/WorkspacePageHeader.tsx
Labels: FE, refactor

#236 🐛 fix: css클래스 삭제 후 똑같은 이름으로 생성 후 css 부여 시 에러 발생하는 버그 수정
  apps/client/src/core/styleFlyout.ts
Labels: FE, fix

#237 [#223] 스토리북 처리 안 되어있던 컴포넌트들 스토리북 추가
  apps/client/src/entities/home/GuideVideo/GuideVideo.stories.tsx
  apps/client/src/entities/home/GuideVideo/GuideVideo.tsx
  apps/client/src/entities/home/WorkspaceSampleButton/WorkspaceSampleButton.stories.tsx
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/ImageTagModalButton/ImageTagModalButton.stories.tsx
  apps/client/src/entities/workspace/ImageTagModalHeader/ImageTagModalHeader.stories.tsx
  apps/client/src/entities/workspace/ImageTagModalImg/ImageTagModalImg.stories.tsx
  apps/client/src/entities/workspace/ImageTagModalList/ImageTagModalList.stories.tsx
  apps/client/src/entities/workspace/ImageTagModalListItem/ImageTagModalListItem.stories.tsx
  apps/client/src/pages/ErrorPage/ErrorPage.stories.tsx
  apps/client/src/shared/blockly/defineBlocks.ts
  apps/client/src/shared/blockly/htmlBlockContents.ts
  apps/client/src/shared/ui/error/ErrorContent.stories.tsx
  apps/client/src/widgets/home/Banner/Banner.stories.tsx
  apps/client/src/widgets/home/GuidesBox/GuidesBox.stories.tsx
  apps/client/src/widgets/home/GuidesBox/GuidesBox.tsx
  apps/client/src/widgets/index.ts
  apps/client/src/widgets/workspace/CoachMark/CoachMark.stories.tsx
  apps/client/src/widgets/workspace/ImageTagModal/ImageTagModal.stories.tsx
  apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.stories.tsx
Labels: FE, test

#239 [#238] 홈페이지 초기 로딩 시 스켈레톤 UI 적용 및 code-highlighter 컴포넌트 스토리북 제작
  README.md
  apps/client/src/shared/code-highlighter/components/CodeContent/CodeContent.stories.tsx
  apps/client/src/shared/code-highlighter/components/CodeContent/CodeContent.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer/CodeViewer.stories.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer/CodeViewer.tsx
  apps/client/src/shared/code-highlighter/components/LineNumbers/LineNumber.stories.tsx
  apps/client/src/shared/code-highlighter/components/LineNumbers/LineNumbers.tsx
  apps/client/src/shared/code-highlighter/index.ts
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/useInfiniteScroll.ts
  apps/client/src/shared/hooks/usePreventLeaveWorkspacePage.ts
  apps/client/src/widgets/home/WorkspaceContainer/WorkspaceContainer.tsx
Labels: FE, chore

#241 [#155] 워크스페이스 캔버스, html 태그, css 클래스 블록 우클릭 시 발생하는 에러 해결, CSS 툴박스 input창 클릭 시 에러 발생 해결
  apps/client/src/core/styleFlyout.ts
  apps/client/src/core/tabbedToolbox.ts
  apps/client/src/shared/blockly/createCssClassBlock.ts
  apps/client/src/shared/blockly/defineBlocks.ts
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
Labels: FE, fix

#243 [HOTFIX] 툴박스 카테고리가 선택안되는 문제 해결
  apps/client/src/core/tabbedToolbox.ts
Labels: FE, fix

#244 [#240] 사용자 가이드 하이라이팅 컴포넌트가 모달에서도 하이라이팅
  apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/shared/store/useCoachMarkStore.ts
  apps/client/src/shared/utils/tags.ts
  apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
  apps/client/src/widgets/workspace/WorkspacePageHeader/WorkspacePageHeader.tsx
Labels: bug, FE

#245 [hotfix] 메타 태그 인식되지 않는 문제 해결
  apps/client/src/app/App.tsx
  apps/client/src/pages/HomePage/HomePage.tsx
  apps/client/src/pages/NotFound/NotFound.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
Labels: fix
